udapi/block/write/conllu.py, udapi/core/tests/data/UD_Czech_sample.conllu, udapi/core/tests/data/secondary_dependencies.conllu, udapi/core/tests/external_tests.sh
Fixes #24.
So now writing to STDOUT works with Python3 as well.
Also, the last line in each conllu file must be empty.
=> Python2+3 way of writing utf8 files

udapi/block/demo/rehangprepositions.py, udapi/block/read/conllu.py, udapi/block/read/reducedconllu.py, udapi/block/write/conllu.py, udapi/block/zellig_harris/baseline.py, udapi/core/basereader.py, udapi/core/block.py, udapi/core/bundle.py, udapi/core/document.py, udapi/core/node.py, udapi/core/root.py, udapi/core/tests/test_node.py
WIP: more commits will follow.
Unfortunately, I don't have time to pack the refactoring into neat commented commits
because there are so many bugs and things to change.
=> Review core

udapi/block/zellig_harris/common.py, udapi/block/zellig_harris/configurations.py, udapi/block/zellig_harris/csnouns.py, udapi/block/zellig_harris/csverbs.py, udapi/block/zellig_harris/enhancedeps.py, udapi/block/zellig_harris/ennouns.py, udapi/block/zellig_harris/enverbs.py, udapi/block/zellig_harris/queries.py
* the __init__ were wrong (args not used anymore) and moreover not needed
If there are any extra block parameters, it should be
def __init__(self, extra_param=default_value, **kwargs):
super().__init__(**kwargs)
self.extra_param = extra_param
* configurations.py did not import sys, I think raise is better than sys.exit here
TODO:
* wildcard and unused imports
=> fix some pylint errors in zellig-harris

udapi/block/read/conllu.py, udapi/block/write/conllu.py, udapi/block/write/textmodetrees.py, udapi/core/basereader.py, udapi/core/basewriter.py, udapi/core/dualdict.py, udapi/core/feats.py, udapi/core/node.py, udapi/core/root.py, udapi/core/tests/test_node.py
```python
>>> node = Node()
>>> str(node.feats)
'_'
>>> node.feats = {'Case': 'Nom', 'Person': '1'}`
>>> node.feats = 'Case=Nom|Person=1' # equivalent to the above
>>> node.feats['Case']
'Nom'
>>> node.feats['NonExistent']
''
>>> node.feats['Case'] = 'Gen'
>>> str(node.feats)
'Case=Gen|Person=1'
>>> dict(node.feats)
{'Case': 'Gen', 'Person': '1'}
```
`node.misc` works the same as `node.feats`, only `feats` will have few more syntactic sugar methods, e.g. `node.feats.is_plural()`.
This way, we don't need `node.raw_feats`.
=> Feats and misc implemented using DualDict

udapi/block/ud/google2ud.py
I do not know a universal solution so I suggest to use `dep:prt` elsewhere to not lose the annotation and be able to act later.
=> Compound:prt is for Germanic languages only

udapi/block/write/tikz.py, udapi/core/node.py
After this PR, you can do e.g. `write.Tikz attributes=upos,misc[SpaceAfter],gloss comment_attribute=text_en`
Future work: adapt `root.comment`, so it is a DualDict similar to `node.feats` and `node.misc`, but with different stringification, so you could use e.g. `tree.comment["text_en"]`.
=> Easier access to node.gloss etc.

udapi/core/node.py, udapi/core/tests/test_enhdeps.py
Simple fix to [Issue 62](https://github.com/udapi/udapi-python/issues/62). The fix is minimal and trivial: replace the modulo `%d` operator with `"{}:{}".format()` in the function that creates the `raw_deps` (Python 3 is already a requirement for `udapi-python`).
I tested the fix with:
* `core/tests/test_nodes.py`
* `core/tests/test_enhdeps.py` (created by me)
=> Francesco Mambrini

udapi/block/ud/markbugs.py
A solution for #64.
If other languages are discovered in the future for which `VerbForm` is not required, they will have to be added manually here.
=> Markbugs langspec

udapi/__init__.py, udapi/core/block.py, udapi/core/document.py, udapi/core/run.py
For example to print subjects with more than 4 children:
```
import udapi
doc = udapi.Document("UD_English/sample.conllu")
subjects = [n for n in doc.nodes if n.deprel == 'nsubj']
for subject in subjects:
if len(subject.children) > 4:
subject.print_subtree()
```
=> make Udapi easier to use from IPython

udapi/tool/udpipe.py
Calling `tokenize_tag_parse_tree` with `resegment=False` first runs the underlying UDPipe, resulting in a sequence of tokens potentially grouped to sentence segments. The nested sequence is then flatten so that all tokens belong to the same segment. However, this was not reflected in the `root.text` attribute, which was always assigned a value from UDPipe by calling `ufal.udpipe.Sentence.getText()`. Apparently, instead of recomputing the return value on the fly, the getter returns a value pre-computed during processing.
If we do not want the text to be resegmented, the value of `root.text` must stay the same.
=> If resegment=False, the root.text should not contain only the first sentence

udapi/block/tokenize/onwhitespace.py
Use the parameter `normalize_spaces=False` to preserve all whitespaces in the sentence in the UDPipe way, i.e. using the `SpacesAfter` and `SpacesBefore` features in the MISC field. It is backward compatible with CoNLL-U v2 `SpaceAfter=No` feature. That is, a missing space after the token is marked by `SpaceAfter=No`, even if it follows the last token of the sentence, and a single space after the token results in no whitespace-related markup at all.
Examples:
```
$> echo -e "Hello \t world " | udapy read.Sentences $'rstrip=\r\n' tokenize.OnWhitespace normalize_spaces=0 write.Conllu
1       Hello   _       _       _       _       0       _       _       SpacesAfter=\s\t\s
2       world   _       _       _       _       0       _       _       _
$> echo -e "Hello \t world" | udapy …
```
=> Whitespaces can be stored in the conllu file, so that the original text can be reconstructed back

udapi/block/segment/simple.py
1. deal with multiple consecutive spaces in input sentences or the space at the start/end of the sentence
=> no sentence boundary
2. do not strip possible trailing space from the sentence. When applying tokenize.Simple afterwards with normalize_spaces=0, it correctly fills the whitespace-related MISC features => the text can be reconstructed in its original form
3. if an abbreviation of the first name is the first word of a quoted segment, delete the starting quotation mark to find out if the word consists of two chars, e.g. in "„A. Merkel ..."
=> Improvements to Simple segmenter

udapi/block/read/sentences.py, udapi/block/tokenize/onwhitespace.py, udapi/block/write/conllu.py
These changes are related only to the documents that are read using `read.Sentences` with parameter `rstrip=''`, `rstrip='\n'` or `rstrip='\r\n'`.
1. The most important is preventing printing out the unescaped whitespace by `write.Conllu`. It has been already implemented that if `tokenize.OnWhitespace keep_spaces=1` or `udpipe.Base` is used, the whitespace is escaped and preserved in MISC features `SpaceAfter`, `SpacesAfter` and `SpacesBefore`. Here we address the `Root.text` attribute, which contains all whitespaces in the unescaped form throughout whole processing. These, however, need to be removed or escaped during writing to CoNLL-U format. **We have now decided to remove all '\n' and '\r' from the whole `Root.text` attribute and strip the whitespaces from its end.** Multiple spaces …
=> Adjustments to correctly work with texts loaded with whitespace included

udapi/block/corefud/indexclusters.py
A block to re-index coreference clusters.
Does not work correctly, until #77 is not merged.
=> Reindex clusters

udapi/block/corefud/fixcorefud02.py, udapi/block/corefud/fixinterleaved.py, udapi/block/corefud/gum2corefud.py, udapi/block/corefud/indexclusters.py, udapi/block/corefud/load.py, udapi/block/corefud/markcrossing.py, udapi/block/corefud/markinterleaved.py, udapi/block/corefud/marknested.py, udapi/block/corefud/marksamesubspan.py, udapi/block/corefud/mergesamespan.py, udapi/block/corefud/movehead.py, udapi/block/corefud/printclusters.py, udapi/block/corefud/printentities.py, udapi/block/corefud/printmentions.py, udapi/block/corefud/stats.py, udapi/block/read/oldcorefud.py, udapi/block/util/eval.py, udapi/block/write/oldcorefud.py, udapi/core/block.py, udapi/core/coref.py, udapi/core/document.py, udapi/core/node.py, udapi/core/tests/test_coref.py
* `CorefCluster` -> `CorefEntity`
* `mention.cluster` -> `mention.entity`
* `cluster.cluster_id` -> `entity.eid`
* `cluster.cluster_type` -> `entity.etype`
* `for cluster in doc.coref_clusters.values():` -> `for entity in doc.coref_entities:`
* `for cluster_id, cluster in data.coref_clusters.items():` -> `for eid, entity in doc.eid_to_entity:`
* rename also clusters/cluster -> entities/entity almost everywhere else (variable and parameter names, comments,...)
* new udapi.core.block methods `process_coref_mention` and `process_coref_entity`
=> Rename cluster to entity

udapi/core/node.py
Shift before node's documentation seems to be the same as shift after node where the direction does not read correctly.
=> Fix a tiny typo

udapi/block/write/tikz.py
With `enhanced=1`, the enhanced graph will be printed under the text.
Example:
=> Support printing enhanced graphs in Tikz

udapi/block/write/corefhtml.py, udapi/core/basewriter.py
In the `write.corefhtml` package, the `docs_dir` parameter is supposed to contain a path relative to the directory where the HTML file is output. However, this is violated when the output directory is not the current working directory.
The fix introduces `js_docs_dir` which should always contain a relative path to be used in the JS scripts. On the other hand, if the output directory is specified using the `path` parameter, the `docs_dir` is adjusted so that it is relative to the output path.
For the time being, it only works if the `path` parameter is specified. It is not adjusted if the output directory is specified using the `files` parameter.
=> Corefhtml writer: use a relative docs_dir path in the JS script

udapi/block/corefud/delete.py
The current solution of deleting enhanced dependencies (`deps` field) to empty parents fails in validation tests with a few error of the following type:
```
[(in cs_pcedt-ud-test-blind.conllu) Line 62051 Sent wsj2387-001-p1s47]: [L2 Enhanced unconnected-egraph] Enhanced graph is not connected. Nodes ['34', '35', '36', '37', '38', '39', '40', '41'] are not reachable from any root
Enhanced errors: 1
*** FAILED *** with 1 errors
```
The reason is that it just deletes the dependencies to empty parents and replaces them with a dependency to "0:root" only if no other has left. However, exceptionally it happens that a dependency to an empty parent is the only connection of a set of nodes to the rest of the tree, making them unreachable from the root after deleting the empty parent. 
The …
=> Recursively searching for non-empty ancestors of enhanced dependencies with empty parents

udapi/core/run.py
Factoring out the execution of blocks from the `Run.execute` will allow users to run their scenarios from Python and use user-initialized blocks directly without the need to parse string scenarios.
=> Split the execute method in Run
